# Generated by Django 5.0 on 2023-12-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_user_verification_code_user_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
